.bumpversion.cfg, .github/workflows/publish-release.yml, .reuse/dep5, src/fosslight_reuse/_fosslight_reuse.py
- Automatically update version in setup.py on release.
- Update the help message link.
=> Update version in setup.py when release

README.md, src/fosslight_reuse/_add.py, src/fosslight_reuse/_fosslight_reuse.py, src/fosslight_reuse/_help.py, src/fosslight_reuse/cli.py, tests/add/test_add.py, tox.ini
- Print file lists that have both license and copyright
- Add license / copyright at the header of missing license / copyright file
- Add manual and automatic mode to add copyright / license
=> Apply add mode to add license and copyright

src/fosslight_reuse/_add.py, src/fosslight_reuse/_fosslight_reuse.py
=> Apply f-string format

src/fosslight_reuse/_fosslight_reuse.py, src/fosslight_reuse/_result.py
- Add excution error result
- Bug fix about output file name when using -o option
< Example of xml >
```
<?xml version='1.0' encoding='UTF-8'?>
<results><error id="rule_key_osc_checker_01" line="0" msg="&#10;# SUMMARY&#10;* Open Source Package File: &#10;                                * Detected Licenses : -, GPL-3.0-only&#10;                                * Files without copyright : 5 / 16&#10;                                * Files without license : 5 / 16&#10;&#10;&#10;Ref. Copyright and License Writing Rules in Source Code. : https://oss.lge.com/guide/process/osc_process/1-identification/copyright_license_rule.html" /><execution_errors><execution_error>Can't find oss-pkg-info file</execution_error><execution_error>Can't find a path</execution_error></execution_errors></results>
``` …
=> Add excution error result

src/fosslight_oss_pkg/_parsing_excel.py, src/fosslight_reuse/_fosslight_reuse.py
Fix the bug that Excel cannot be created if there is only one row in Convert mode.
=> Fix the bug that Excel cannot be created if there is only one row in Convert mode

src/fosslight_reuse/_constant.py, src/fosslight_reuse/_fosslight_reuse.py, src/fosslight_reuse/_result.py
Check compliant except for files for which Exclude is True.
=> Check compliant except for files for which Exclude is True

src/fosslight_oss_pkg/_parsing_excel.py, src/fosslight_oss_pkg/fosslight_oss_pkg.py, src/fosslight_reuse/_help.py, src/fosslight_reuse/cli.py
- Multiple sheet names can be entered with the -s option. (ex. SRC, BIN)
- If user does not enter the -s option, convert all sheets starting with SRC, BIN, and BOM.
=> Make the sheet to convert selectable. (-s sheet name option)

src/fosslight_reuse/_constant.py, src/fosslight_reuse/_result_html.py
- Add expand button in html when the number of licenses or oss-pkg-files exceeds 100
=> Add expand button in html

requirements.txt, src/fosslight_reuse/_add.py, src/fosslight_reuse/_constant.py, src/fosslight_reuse/_fosslight_reuse.py, src/fosslight_reuse/_result.py
- Changed logic to find and remove files excluded from yaml
- AS-IS: Find list of files to exclude from yaml in files without license/copyright and remove them later.
- TO-BE: If you find a file to be excluded from yaml in a file without license/copyright, remove it immediately.
- OSS Package file is excluded from the list of files without license/copyright
- The name of the yaml file to parse:
- AS-IS: oss-pkg-info.yaml
- TO-BE: oss-pkg-info*.yaml
- How to match against files written to yaml:
- AS-IS: File name pattern match using fnmath
- TO-BE: Match the file name pattern using fnmath, and if it does not match, match regular expression
Reason: When only the folder name is written (ex. In case of temp, to match all temp/*)
- Fixed bug where oss-pkg-info*.yaml file could not be found in …
=> Apply fnmatch / re match to match file name

src/fosslight_oss_pkg/_parsing_excel.py, src/fosslight_oss_pkg/fosslight_oss_pkg.py, src/fosslight_reuse/_help.py, src/fosslight_reuse/cli.py
- Add -v option to print FOSSLight Reuse version
- Add error handling code in convert mode
- Print creating file log when only write output_file successfully, or not exit system
- Check file name in convert mode (oss-pkg-info*.yaml file)
- Delete creating .csv file
=> Add -v option and error handling in convert mode

src/fosslight_oss_pkg/_convert.py, src/fosslight_oss_pkg/_parsing_excel.py, src/fosslight_prechecker/_help.py, src/fosslight_prechecker/cli.py, tox.ini
- Remove convert_excel_to_yaml code(moved to FL Util)
=> Remove the function to convert excel to yaml

src/fosslight_prechecker/_precheck.py, src/fosslight_prechecker/_result.py
Change the exit code to a constant for windows support.
- os.EX_** : Exit Code is for UNIX. (https://docs.python.org/3/library/os.html)
=> Change the exit code to a constant for windows

src/fosslight_prechecker/_result.py
- Fix a bug where the path defined in sbom-info.yaml is not excluded from lint results.
=> Fix bug where path in sbom-info.yaml is not excluded from lint result

src/fosslight_prechecker/cli.py
- Fix not to print argparse's help msg when command error
=> Fix not to print argparse's help msg

.github/workflows/publish-release.yml, .github/workflows/pull-request.yml, setup.py, src/fosslight_prechecker/_help.py, src/fosslight_prechecker/cli.py, tox.ini
Signed-off-by: Jiyeong Seok <jiyeong.seok@lge.com>
Print license text through notice parameter
=> Print license text through notice parameter

.github/workflows/publish-release.yml, .github/workflows/pull-request.yml, cli.py, src/fosslight_prechecker/_precheck.py
- Modify to run all mode on Windows
- Replace windows path separator '\\' to '/' when write .dep5 file
=> Modify to run all mode on Windows

src/fosslight_prechecker/_precheck.py
Fix Dep5 encoding error.
- How to reproduce the bug : If you run the executable created with pyinstaller on windows, it will be reproduced. This bug causes the total file count to be less than the unlicensed file count.
=> Fix Dep5 encoding error

src/fosslight_prechecker/_result.py
- Replace windows operator to '/' for path in yaml
=> Replace windows operator to '/' for path in yaml

src/fosslight_prechecker/_precheck.py
- Add git ignore option(-c) for excluding
- -c, --cached optioin : show cached files in the output (default)
- on Windows, It occurs to error to get files in .gitignore without -c option
- on Ubuntu, it's possible to get files in .gitginore regardless of -c option
=> Add git ignore option(-c) for excluding

src/fosslight_prechecker/_precheck.py
- Modify 'Analyze path' if input file on lint
- Change logger level about excluding git file
=> Modify 'Analyze path' if input file on lint

src/fosslight_prechecker/_result.py
- Replace windows path separator to linux's('\\\\' -> '/') regardless of OS
- Log the pattern when find unmatched pattern
=> Fix to error about escape character

CHANGELOG.md, setup.py, src/fosslight_oss_pkg/_convert.py, src/fosslight_oss_pkg/_parsing_excel.py, src/fosslight_prechecker/_add.py, src/fosslight_prechecker/_help.py, src/fosslight_prechecker/_precheck.py, src/fosslight_prechecker/_result.py, src/fosslight_prechecker/_result_html.py, src/fosslight_prechecker/cli.py
Add type hints to each function.
=> Add type hints to each function

src/fosslight_prechecker/_add.py, src/fosslight_prechecker/_add_header.py, src/fosslight_prechecker/_precheck.py, src/fosslight_prechecker/cli.py
- Print option name with error msg
=> Print option name with error msg

requirements.txt, src/fosslight_prechecker/_add.py, src/fosslight_prechecker/_precheck.py, src/fosslight_prechecker/cli.py
- Import exclude path fct. from FL util
- https://github.com/fosslight/fosslight_util/pull/207
=> Import exclude path fct. from FL util

requirements.txt, src/fosslight_prechecker/_add.py, src/fosslight_prechecker/_download_lic.py, src/fosslight_prechecker/_help.py, src/fosslight_prechecker/cli.py
- Add 'Download' mode to download license text
- 'Download' mode
- can use '-l' option
- -l <license> : License to be representative license 
- if there is already representative license file, print the license name and path
- or not, download input license text file as representative license
- Remove code for download license text from '_add.py' file
=> Add 'Download' mode to download license text
