fosslight/fosslight_prechecker

.github/workflows/publish-release.yml
Remove waring in publish-release.yml
=> Remove waring in publish-release.yml

.github/workflows/publish-release.yml
Bug fix to checkout new version
=> Bug fix to checkout new version

requirements.txt
Set condition to use FOSSLight Util v1.1.0 or later
=> Set condition to use FOSSLight Util v1.1.0 or later

.github/workflows/publish-release.yml
Fix a bug related release action.
- Create an executable with the updated version information.
=> Fix a bug related release action

src/fosslight_reuse/_add.py, src/fosslight_reuse/_help.py, src/fosslight_reuse/cli.py, tests/add/test_both_have_1.py, tests/add/test_both_have_2.py, tests/add/test_no_copyright.py, tests/add/test_no_license.py, tox.ini
Remove the -m option and request the input from the user if -c or -l is null in add mode.
=> Delete -m option

.reuse/dep5, MANIFEST.in, setup.py, src/fosslight_oss_pkg/_parsing_yaml.py, src/fosslight_reuse/_add.py, src/fosslight_reuse/_fosslight_reuse.py, src/fosslight_reuse/resources/convert_license.json, tests/add/oss-pkg-info.yaml, tox.ini
- Download representative license file if there is no representative license
- Download all licenses text file in OSS-pkg-info.yaml
- Add to download license text in tox.ini
=> Add code of downloading license text

README.md, src/fosslight_oss_pkg/_parsing_yaml.py
- Bug fix to create .xlsx file
- Fix url for User Guide
=> Bug fix to create .xlsx file

src/fosslight_oss_pkg/_parsing_excel.py
- Add sheet name(BIN(Yocto)) to use Yocto report
=> Add sheet name(BIN(Yocto)) to use Yocto report

src/fosslight_reuse/cli.py
- Fix to print help message if don't write mode
=> Fix to print help message if don't write mode

.github/PULL_REQUEST_TEMPLATE.md
Comment out some sentences in the PR template.
=> Comment out some sentences in the PR template

src/fosslight_reuse/_add.py
- Change appending list in for loop to using yield
=> Change appending list in for loop to using yield

cli.py, requirements.txt, src/fosslight_oss_pkg/fosslight_oss_pkg.py, src/fosslight_reuse/_add.py, src/fosslight_reuse/_fosslight_reuse.py, src/fosslight_reuse/_help.py, src/fosslight_reuse/cli.py, tox.ini
- -f : Result format type (html, xml, yaml)
- -p : folder path or file path
- Apply changed -f and -p options to all mode
- Generating a result file based on the format (default: yaml)
=> Change -p, -f option

src/fosslight_reuse/_add.py, src/fosslight_reuse/_fosslight_reuse.py, src/fosslight_reuse/_result.py, tox.ini
- Add code of creating yaml result file
- Default result file format : .yaml
- Example :
```
Checking copyright/license writing rules:
Compliant: Not OK
Summary:
Open Source Package File: N/A
Detected Licenses:
- '-'
- GPL-3.0-only
Count without license / Total: 1 / 10
Count without copyright / Total: 1 / 10
Files without license and copyright:
- fosslight_reuse/_add.py
Files without license:
- fosslight_reuse/_add.py
Files without copyright:
- fosslight_reuse/_add.py
Tool Info:
OS Info: Linux 4.15.0-144-generic
Path to analyze: /home/jaekwonbang/fosslight_reuse_0512/src
Python Version: 3
FL Reuse Version: fosslight_reuse v2.1.9
Created file name: /home/jaekwonbang/fosslight_reuse_0512/FOSSLight_Reuse_20220519_11-03-23.yaml
```
=> Add code of creating yaml result file

src/fosslight_oss_pkg/_parsing_excel.py, src/fosslight_reuse/_add.py, src/fosslight_reuse/_fosslight_reuse.py, src/fosslight_reuse/_result.py
- Add creating xml result file
- Fix to lint with file path
- Example of xml
```
<?xml version='1.0' encoding='UTF-8'?>
<results><error id="rule_key_osc_checker_01" line="0" msg="&#10;# SUMMARY&#10;&#09;* Open Source Package File: &#10;&#09;* Detected Licenses : -, GPL-3.0-only&#10;&#09;* Files without copyright : 6 / 16&#10;&#09;* Files without license : 6 / 16&#10;&#10;&#10;Ref. Copyright and License Writing Rules in Source Code. : https://oss.lge.com/guide/process/osc_process/1-identification/copyright_license_rule.html" /></results>
```
=> Add creating xml result file

src/fosslight_oss_pkg/_parsing_excel.py
- Modify function of converting excel to yaml
=> Modify function of converting excel to yaml

src/fosslight_oss_pkg/_parsing_excel.py, src/fosslight_reuse/_add.py, src/fosslight_reuse/_fosslight_reuse.py, tests/convert/oss-pkg-info.yaml
- Apply parsing and convert new yaml format
=> Apply parsing and convert new yaml format

requirements.txt, src/fosslight_oss_pkg/_parsing_excel.py, src/fosslight_reuse/_add.py, src/fosslight_reuse/_fosslight_reuse.py, src/fosslight_reuse/_result.py, tox.ini
- Apply changed parsing_yaml return value
- Modify finding oss package info file for only folder path input(Add mode)
- Add error handling code for not presenting path
=> Apply changed parsing_yaml return value

src/fosslight_oss_pkg/_parsing_excel.py
Modify SRC and BIN Sheet to be convertible.
=> Load SRC Sheet in excel

src/fosslight_oss_pkg/fosslight_oss_pkg.py, src/fosslight_reuse/_add.py, src/fosslight_reuse/_fosslight_reuse.py, src/fosslight_reuse/_result.py, src/fosslight_reuse/cli.py
- Remove duplicate files in w/o license or copyright list
=> Remove duplicate files in w/o license or copyright list

src/fosslight_reuse/_add.py, src/fosslight_reuse/cli.py
- Apply -o option in add mode to save log.txt file
=> Apply -o option in add mode

src/fosslight_reuse/_constant.py, src/fosslight_reuse/_fosslight_reuse.py, src/fosslight_reuse/_result.py
- Exclude for open source package file in w/o license or copyright list
- Fix typo : Excution -> Execution
- Fix to run lint mode with file input
=> Exclude for open source package file in w/o list

src/fosslight_oss_pkg/fosslight_oss_pkg.py, src/fosslight_reuse/_add.py, src/fosslight_reuse/_fosslight_reuse.py, src/fosslight_reuse/_help.py, src/fosslight_reuse/cli.py
Add the i (--ignore) option to not create a log file.
=> Add the i (--ignore) option to not create a log file.

src/fosslight_reuse/_fosslight_reuse.py
- Modification for compliance with pep8
=> Modification for compliance with pep8

requirements.txt
- update the minimum version of fosslight_util
=> update the minimum version of fosslight_util

src/fosslight_reuse/_add.py, src/fosslight_reuse/_constant.py, src/fosslight_reuse/_fosslight_reuse.py
- Exclude for sbom info yaml file in Lint mode
=> Exclude for sbom info yaml file in Lint mode

src/fosslight_reuse/_fosslight_reuse.py
- Change path to analyze path to print in lint mode
=> Change path to analyze path to print in lint mode

src/fosslight_reuse/_constant.py, src/fosslight_reuse/_fosslight_reuse.py, src/fosslight_reuse/_result.py, src/fosslight_reuse/_result_html.py
- Add generating html format file
- Add '_result_html.py' file to make html file
1. Normal Case
2. more than 100 incompliant files
=> Add generating html format file

src/fosslight_reuse/_result_html.py
- Add execution error handling for html.
=> Add execution error handling for html

cli.py, setup.py, src/fosslight_oss_pkg/fosslight_oss_pkg.py, src/fosslight_reuse/_add.py, src/fosslight_reuse/_constant.py, src/fosslight_reuse/_fosslight_reuse.py, src/fosslight_reuse/_help.py, src/fosslight_reuse/_result_html.py, src/fosslight_reuse/cli.py
- Modify html format when files exceeds 100
- If compliant, do not print table row header
- Apply -f option in convert mode
- Modify -i option to disable progress bar
=> Modify html format when files exceeds 100

src/fosslight_reuse/_constant.py
Remove gray background from html.
=> Remove gray background from html

src/fosslight_reuse/_constant.py
Change it to a responsive table and change the width to 100% of the screen.
- AS-IS: 
- TO-BE:
=> Change it to a responsive table

src/fosslight_reuse/_constant.py
=> Remove scroll from html

requirements.txt, src/fosslight_oss_pkg/_parsing_excel.py
- Move read excel code to FL Util
=> Move read excel code to FL Util

requirements.txt
=> Remove unused packages

README.md
- Modify badge info in README.md
=> Modify badge info in README.md

src/fosslight_oss_pkg/_parsing_excel.py
Change the message if there is nothing to convert.
=> Change the message if there is nothing to convert

tests/convert/oss-pkg-info.yaml, tests/convert/oss-pkg-info_old.yaml
- Add new format of oss-pkg-info.yaml
=> Add new format of oss-pkg-info.yaml

src/fosslight_oss_pkg/_parsing_excel.py
This is an update according to the PR modified by FL Util (https://github.com/fosslight/fosslight_util/pull/81/files).
=> Delete unnecessary returns

src/fosslight_oss_pkg/_convert.py, src/fosslight_prechecker/_help.py, src/fosslight_prechecker/cli.py
- Run current path if no input path (add, lint mode)
=> Run current path if no input path

src/fosslight_oss_pkg/_convert.py
=> Remove unnecessary code

src/fosslight_prechecker/cli.py
- Fix to print argparse help msg if input no mode
=> Fix to print argparse help msg if input no mode

README.md, src/fosslight_oss_pkg/_convert.py, src/fosslight_prechecker/_add.py, src/fosslight_prechecker/_precheck.py, src/fosslight_prechecker/_result.py
- Modify result file name format
-  lint mode : fosslight_lint_220905_1237
-  convert mode : fosslight_report_220905_1237
- Modify result file name log file
- fosslight_log_220905_1237.txt
- fosslight_log_add_220905_1237.txt
=> Modify result file name format

src/fosslight_oss_pkg/_parsing_excel.py
**Convert multiple yaml files into one report.**
- Change sheet name
-  If it is more than 30 charactres, cut it down to 31 characters.
-  If there is the same path up to 31 characters, add numbering at the end of the name.
=> Convert multiple yaml files into one report

src/fosslight_prechecker/_constant.py
- Add OSS pkg file list for Nuget
=> Add OSS pkg file list for Nuget

src/fosslight_prechecker/_precheck.py
- Fix bug in lint and add error for Windows
=> Fix bug in lint and add error for Windows

src/fosslight_prechecker/cli.py
- Fix a bug that does not run if the mode value is not entered.
=> Fix bug that doesn't work -v, -h option

README.md, requirements-dev.txt, src/fosslight_prechecker/_add.py, src/fosslight_prechecker/_constant.py, src/fosslight_prechecker/_help.py, src/fosslight_prechecker/_precheck.py, src/fosslight_prechecker/cli.py
- Fix bug for not working options(-n, i) and print help message
- Set lint mode to default mode.
- Not print progress bar in add mode when interactive working
=> Fix bug for not working options(-n, i)

src/fosslight_prechecker/_help.py, src/fosslight_prechecker/_precheck.py, src/fosslight_prechecker/_result.py
- Exclude untracked files and ignored files in lint mode
- Default : exclude 
- Disable to exclude those files by using -n option 
- Excluded file list
- all files specified in .gitignore
- untracked files
- hidden files
- Fix bug about calculating the number of total files
- Subtract exclude files
=> Exclude untracked files and ignored files in lint mode

src/fosslight_prechecker/_precheck.py, src/fosslight_prechecker/_result.py
- Exclude untracked files in input path
=> Exclude untracked files in input path

src/fosslight_prechecker/_add.py, src/fosslight_prechecker/_precheck.py, src/fosslight_prechecker/cli.py, src/fosslight_prechecker/resources/convert_license.json
- Modify downloading the license text
- First download from reuse-tool
- If failed, download from LGE url
- Add exit code if input -c or -l, when not add mode
=> Modify downloading the license text

src/fosslight_prechecker/_result.py
- Fix yaml file encoding error.
=> Fix yaml file encoding error

src/fosslight_prechecker/_constant.py, src/fosslight_prechecker/_result.py, tox.ini
- Add *sbom_info*.yaml pattern to OSS_PKG_INFO_FILES.
- Remove '-' from license of lint result.
- Use allowlist_externals instead of whitelist_externals.
=> Add *sbom_info*.yaml pattern to OSS_PKG_INFO_FILES

src/fosslight_prechecker/_constant.py
- Modify to simplify file list in OSS_PKG_FILES
=> Modify to simplify file list in OSS_PKG_FILES

src/fosslight_prechecker/_add.py, src/fosslight_prechecker/_constant.py
- Modify to print file without extension correctly
- Find and create representative license file after add license or copyright
=> Modify to print file wo ext. correctly

src/fosslight_prechecker/_add.py
- Modify to match SPDX regardless of case
=> Modify to match SPDX regardless of case

src/fosslight_prechecker/_add.py
- Download license file regardless of representative license.
=> Download license file regardless of representative license

src/fosslight_prechecker/_add.py
- Bug fix to print file name several times
=> Bug fix not to print no ext. file name

requirements.txt, src/fosslight_prechecker/_add.py, src/fosslight_prechecker/_precheck.py, src/fosslight_prechecker/_result.py
- Modify to check file extension efficiently
- Add condition to download license text file
- Modify to count of total file
=> Modify to check file extension efficiently

src/fosslight_prechecker/_help.py
- Modify typo of example of convert
=> Modify typo of example of convert

src/fosslight_prechecker/_result.py, src/fosslight_prechecker/cli.py
- Modify writing rule url
- Unify version output format
=> Unify version output format

src/fosslight_prechecker/_result.py
- Bug fix to encode html result file
=> Bug fix to encode html result file

src/fosslight_prechecker/_result.py
- Fix bug about contents of xml result
=> Fix bug about contents of xml result

requirements.txt, src/fosslight_oss_pkg/_parsing_excel.py, src/fosslight_prechecker/_add.py, src/fosslight_prechecker/_result.py
- Add yaml error reason to file name
=> Add yaml error reason to file name

src/fosslight_oss_pkg/_convert.py, src/fosslight_prechecker/_add.py, src/fosslight_prechecker/_precheck.py
- Add the pkg name to log and result file
=> Add the pkg name to log and result file

src/fosslight_prechecker/_precheck.py
- Bug fix of same folder name in add, lint mode
=> Bug fix of same folder name in lint and add

src/fosslight_prechecker/_precheck.py
- Modify condition to exclude git ignore file
=> Modify condition to exclude git ignore file

src/fosslight_prechecker/_precheck.py
- Modify path parameter to find VCS root path
=> Modify to find VCS root path 

.github/workflows/publish-release.yml, .github/workflows/pull-request.yml
- Change ubuntu ver. from 18.04 to 20.04
- Change checkout ver. from 3 to 3.4.0
=> Update package version for github actions

requirements.txt
- Apply fosslgiht_util v1.4.23 or later
=> Apply fosslgiht_util v1.4.23 or later

.github/workflows/publish-release.yml
- Fix to find file path for executable
=> Fix to find file path for executable

src/fosslight_prechecker/_add.py, src/fosslight_prechecker/_help.py
- Bug fix to add comment into .txt file
- Not adding comment to .txt file
=> Bug fix to add comment into .txt file

src/fosslight_prechecker/_add.py, src/fosslight_prechecker/_add_header.py
=> Fix the snyk vulnerability

.github/workflows/pull-request.yml
- Use common action flow of follwoing file.
- https://github.com/fosslight/fosslight_scanner/blob/main/.github/workflows/pull-request.yml
=> Use common action flow

requirements.txt, src/fosslight_prechecker/_help.py, src/fosslight_prechecker/_precheck.py, src/fosslight_prechecker/_result.py, src/fosslight_prechecker/cli.py, tox.ini
* Add additional arguments for paths to exclude in cli
* Exclude the specifed directories and files from lint
* Log for excluded paths
* Add test case in tox test
=> Supports for excluding paths in lint mode

src/fosslight_oss_pkg/_parsing_excel.py
Fix a bug related to type.
- Error message :  `TypeError: 'type' object is not subscriptable`
=> Fix a bug related to type

requirements.txt, src/fosslight_oss_pkg/_parsing_excel.py, src/fosslight_prechecker/_result.py
=> Refactoring OSS item

requirements.txt
Change fosslight_util ver limit
=> Change fosslight_util ver limit

.github/workflows/publish-release.yml
=> Fix the github action issue

README.md, src/fosslight_prechecker/_download_lic.py
- Modify README file for download mode
=> Modify README file

src/fosslight_oss_pkg/_parsing_excel.py, src/fosslight_prechecker/_download_lic.py, src/fosslight_prechecker/_help.py, src/fosslight_prechecker/_precheck.py, src/fosslight_prechecker/cli.py, tox.ini
- Modify to download lic. text in sbom-info.yaml from LGE DB w/o -l option
- Run pytest for Flake8 when PR
=> Modify to download lic. text from LGE DB

.github/workflows/publish-release.yml, .github/workflows/pull-request.yml, requirements-dev.txt, setup.py, src/fosslight_prechecker/_add.py, src/fosslight_prechecker/_precheck.py, src/fosslight_prechecker/_result_html.py
Change the minimum Python version to 3.10.
- Python3.9 official support ends in October 25.
=> Change the minimum Python version to 3.10
